services:
  api:
    build:
      context: .
      target: production
    image: cep-service:latest
    environment:
      - CACHE_PROVIDER=redis
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./.env
    ports:
      - '${PORT:-3000}:3000'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -qO- http://localhost:3000${HEALTH_PATH:-/health} || exit 1',
        ]
      interval: 120s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'no']
    restart: unless-stopped
    # Removido o profiles para habilitar o Redis por padrão
